volumes:
  static-data:
  staticfiles-data:
  media-data:

services:
  palette:
    build: .
    container_name: palette-messenger
    volumes:
      - static-data:/static
      - staticfiles-data:/staticfiles
      - media-data:/media
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./docker/prod/nginx/Dockerfile
    container_name: palette-nginx
    ports:
      - '8001:80'
    volumes:
#      - ./nginx/conf:/docker/prod/nginx/django_nginx.conf
      - static-data:/static
      - staticfiles-data:/staticfiles
      - media-data:/media
    depends_on:
      - palette-messenger
    restart: unless-stopped