volumes:
  static-data:
  staticfiles-data:
  media-data:

services:
  palette:
    build: .
    volumes:
      - static-data:/static
      - staticfiles-data:/staticfiles
      - media-data:/media
    env_file:
      - .env
    restart: unless-stopped