services:

  palette:
    build: .
    container_name: palette-messenger
    volumes:
      - ./static:/palette-messenger/static
      - ./staticfiles:/palette-messenger/staticfiles
    env_file:
      - .env
    ports:
      - "8001:8000"
    restart: unless-stopped
volumes:
  postgres_data: