version: '3.8'

volumes:
  static-data:
  staticfiles-data:
  media-data:

services:
  palette:
    build: .
    container_name: palette-messenger
    volumes:
      - static-data:/palette-messenger/static
      - staticfiles-data:/palette-messenger/staticfiles
      - media-data:/palette-messenger/media
    env_file:
      - .env
    restart: unless-stopped
    networks:
      default:
        aliases:
          - palette-messenger

  nginx:
    build:
      context: .
      dockerfile: ./docker/prod/nginx/Dockerfile
    container_name: palette-nginx
    ports:
      - '8001:80'
    volumes:
#      - ./nginx/conf:/docker/prod/nginx/django_nginx.conf
      - static-data:/palette-messenger/static
      - staticfiles-data:/palette-messenger/staticfiles
      - media-data:/palette-messenger/media
    env_file:
      - .env
    depends_on:
      - palette
    restart: unless-stopped