services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  palette:
    build: .
    container_name: palette-messenger
    depends_on:
      - db
    volumes:
      - ./static:/palette-messenger/static
      - ./staticfiles:/palette-messenger/staticfiles
    env_file:
      - .env
    ports:
      - "8001:8001"
    restart: unless-stopped
volumes:
  postgres_data: