# Generated by Django 5.0 on 2025-12-04 20:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('chat_type', models.CharField(choices=[('private', 'Личный'), ('group', 'Группа')], max_length=10, verbose_name='Тип чата')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='chat_avatars/', verbose_name='Аватар группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('file', 'Файл'), ('voice', 'Голосовое')], default='text', max_length=10, verbose_name='Тип сообщения')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('file', models.FileField(blank=True, null=True, upload_to='messages/', verbose_name='Файл')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Отредактировано')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Статус прочтения',
                'verbose_name_plural': 'Статусы прочтения',
            },
        ),
        migrations.CreateModel(
            name='ChatMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('member', 'Участник')], default='member', max_length=10, verbose_name='Роль')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Звук выключен')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее прочтение')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Участник чата',
                'verbose_name_plural': 'Участники чатов',
            },
        ),
    ]
