name: Continuous Deployment Workflow

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: venv
    steps:
      - name: Checkout the commit that triggered CI
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Deploy App to Dokploy
        uses: qbix-tech/dokploy-deploy-action@v1
        with:
          dokploy_url: https://dokploy.messengerpalette.ru
          api_key: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
          application_id: ${{ secrets.DOKPLOY_APPLICATION_ID }}
